Print a message if we could not flush the database.
Signed-off-by: Chris Lamb <chris@playfire.com>

diff --git a/tests/_testcase b/tests/_testcase
--- a/tests/_testcase
+++ b/tests/_testcase
@@ -69,4 +69,9 @@ GET () {
 }
 
 # Flush testing database
-POST /database/${DB}/delete
+if ! POST /database/${DB}/delete
+then
+	echo "Could not flush database; is Swordfish running?"
+
+	return 1
+fi
